// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moviesapp.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4d83b0fc6999f2, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type MovieInfo struct {
	ID                   string    `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Isbn                 string    `protobuf:"bytes,2,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Title                string    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Director             *Director `protobuf:"bytes,4,opt,name=director,proto3" json:"director,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MovieInfo) Reset()         { *m = MovieInfo{} }
func (m *MovieInfo) String() string { return proto.CompactTextString(m) }
func (*MovieInfo) ProtoMessage()    {}
func (*MovieInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4d83b0fc6999f2, []int{1}
}

func (m *MovieInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieInfo.Unmarshal(m, b)
}
func (m *MovieInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieInfo.Marshal(b, m, deterministic)
}
func (m *MovieInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieInfo.Merge(m, src)
}
func (m *MovieInfo) XXX_Size() int {
	return xxx_messageInfo_MovieInfo.Size(m)
}
func (m *MovieInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MovieInfo proto.InternalMessageInfo

func (m *MovieInfo) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *MovieInfo) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *MovieInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MovieInfo) GetDirector() *Director {
	if m != nil {
		return m.Director
	}
	return nil
}

type Director struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Director) Reset()         { *m = Director{} }
func (m *Director) String() string { return proto.CompactTextString(m) }
func (*Director) ProtoMessage()    {}
func (*Director) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4d83b0fc6999f2, []int{2}
}

func (m *Director) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Director.Unmarshal(m, b)
}
func (m *Director) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Director.Marshal(b, m, deterministic)
}
func (m *Director) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Director.Merge(m, src)
}
func (m *Director) XXX_Size() int {
	return xxx_messageInfo_Director.Size(m)
}
func (m *Director) XXX_DiscardUnknown() {
	xxx_messageInfo_Director.DiscardUnknown(m)
}

var xxx_messageInfo_Director proto.InternalMessageInfo

func (m *Director) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Director) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type ID struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4d83b0fc6999f2, []int{3}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Status struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4d83b0fc6999f2, []int{4}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "moviesapp.Empty")
	proto.RegisterType((*MovieInfo)(nil), "moviesapp.MovieInfo")
	proto.RegisterType((*Director)(nil), "moviesapp.Director")
	proto.RegisterType((*ID)(nil), "moviesapp.ID")
	proto.RegisterType((*Status)(nil), "moviesapp.Status")
}

func init() {
	proto.RegisterFile("moviesapp.proto", fileDescriptor_8b4d83b0fc6999f2)
}

var fileDescriptor_8b4d83b0fc6999f2 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4d, 0x6b, 0xf2, 0x40,
	0x10, 0xc7, 0x49, 0x7c, 0xcd, 0xf8, 0x3c, 0xda, 0x4e, 0xa5, 0xa4, 0xa1, 0x14, 0xc9, 0xc9, 0x53,
	0x6c, 0x95, 0x5e, 0x7a, 0xd3, 0xa6, 0x94, 0x50, 0x04, 0xb1, 0x78, 0xe9, 0x6d, 0xd5, 0xb5, 0x04,
	0x12, 0x77, 0xc9, 0xae, 0x01, 0xbf, 0x4a, 0x8f, 0xfd, 0xa4, 0x25, 0x9b, 0x57, 0x5b, 0x6f, 0xce,
	0x6f, 0xe6, 0xe7, 0xfc, 0x33, 0x2c, 0xf4, 0x42, 0x16, 0xfb, 0x54, 0x10, 0xce, 0x1d, 0x1e, 0x31,
	0xc9, 0xd0, 0x28, 0x80, 0xdd, 0x82, 0xc6, 0x4b, 0xc8, 0xe5, 0xd1, 0x8e, 0xc1, 0x98, 0x27, 0xd4,
	0xdb, 0xef, 0x18, 0x76, 0x41, 0xf7, 0x5c, 0x53, 0x1b, 0x68, 0x43, 0x63, 0xa9, 0x7b, 0x2e, 0x22,
	0xd4, 0x7d, 0xb1, 0xde, 0x9b, 0xba, 0x22, 0xea, 0x37, 0xf6, 0xa1, 0x21, 0x7d, 0x19, 0x50, 0xb3,
	0xa6, 0x60, 0x5a, 0xe0, 0x08, 0xda, 0x5b, 0x3f, 0xa2, 0x1b, 0xc9, 0x22, 0xb3, 0x3e, 0xd0, 0x86,
	0x9d, 0xf1, 0x95, 0x53, 0xae, 0x77, 0xb3, 0xd6, 0xb2, 0x18, 0xb2, 0x5d, 0x68, 0xe7, 0x14, 0x6f,
	0xc1, 0xd8, 0xf9, 0x91, 0x90, 0x7b, 0x12, 0xd2, 0x6c, 0x7b, 0x09, 0xd0, 0x82, 0x76, 0x40, 0xb2,
	0x66, 0x1a, 0xa4, 0xa8, 0x6d, 0x2b, 0x09, 0x9c, 0x44, 0x8a, 0x49, 0x70, 0xc8, 0xdd, 0xb4, 0xb0,
	0xef, 0xa0, 0xf9, 0x2e, 0x89, 0x3c, 0x88, 0xd3, 0x7e, 0x23, 0xeb, 0x8f, 0xbf, 0x74, 0x68, 0xad,
	0x78, 0xcc, 0x24, 0x15, 0xf8, 0x08, 0xc6, 0x2b, 0x95, 0xea, 0x10, 0x02, 0x2f, 0x2a, 0xc9, 0xd5,
	0x91, 0xac, 0x7e, 0x85, 0x14, 0xd7, 0xba, 0xd7, 0x70, 0x02, 0xff, 0x72, 0x6d, 0x76, 0xf4, 0x5c,
	0xfc, 0x5f, 0x99, 0xf3, 0xdc, 0xf3, 0x1a, 0x8e, 0xa1, 0xf3, 0x1c, 0x51, 0x22, 0xa9, 0x42, 0x78,
	0x76, 0xc8, 0x3a, 0xfd, 0x27, 0x7c, 0x82, 0xde, 0x8a, 0x6f, 0x73, 0x47, 0xed, 0x3a, 0xef, 0x5d,
	0x56, 0x68, 0xf6, 0xf5, 0x13, 0xe8, 0xb9, 0x34, 0xa0, 0x55, 0xf7, 0x57, 0xce, 0xbf, 0xd2, 0xec,
	0x0d, 0xae, 0x7d, 0xe6, 0x7c, 0x46, 0x7c, 0xe3, 0x10, 0xce, 0x1f, 0xca, 0x81, 0x59, 0x37, 0xbd,
	0xd2, 0x94, 0xf3, 0x45, 0xf2, 0xa8, 0x16, 0xda, 0xc7, 0x4d, 0x69, 0x6f, 0x58, 0x38, 0x4a, 0xa4,
	0x91, 0x7a, 0x70, 0xe2, 0x5b, 0xaf, 0xcd, 0xa7, 0x8b, 0x75, 0x53, 0x55, 0x93, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x6b, 0x2b, 0x83, 0xff, 0x91, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UpvotesClient is the client API for Upvotes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UpvotesClient interface {
	GetMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Upvotes_GetMoviesClient, error)
	GetMovieByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*MovieInfo, error)
	CreateMovie(ctx context.Context, in *MovieInfo, opts ...grpc.CallOption) (*ID, error)
	UpdateMovieByID(ctx context.Context, in *MovieInfo, opts ...grpc.CallOption) (*Status, error)
	DeleteMovieByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Status, error)
}

type upvotesClient struct {
	cc grpc.ClientConnInterface
}

func NewUpvotesClient(cc grpc.ClientConnInterface) UpvotesClient {
	return &upvotesClient{cc}
}

func (c *upvotesClient) GetMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Upvotes_GetMoviesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Upvotes_serviceDesc.Streams[0], "/moviesapp.Upvotes/GetMovies", opts...)
	if err != nil {
		return nil, err
	}
	x := &upvotesGetMoviesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Upvotes_GetMoviesClient interface {
	Recv() (*MovieInfo, error)
	grpc.ClientStream
}

type upvotesGetMoviesClient struct {
	grpc.ClientStream
}

func (x *upvotesGetMoviesClient) Recv() (*MovieInfo, error) {
	m := new(MovieInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *upvotesClient) GetMovieByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*MovieInfo, error) {
	out := new(MovieInfo)
	err := c.cc.Invoke(ctx, "/moviesapp.Upvotes/GetMovieByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upvotesClient) CreateMovie(ctx context.Context, in *MovieInfo, opts ...grpc.CallOption) (*ID, error) {
	out := new(ID)
	err := c.cc.Invoke(ctx, "/moviesapp.Upvotes/CreateMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upvotesClient) UpdateMovieByID(ctx context.Context, in *MovieInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/moviesapp.Upvotes/UpdateMovieByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upvotesClient) DeleteMovieByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/moviesapp.Upvotes/DeleteMovieByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpvotesServer is the server API for Upvotes service.
type UpvotesServer interface {
	GetMovies(*Empty, Upvotes_GetMoviesServer) error
	GetMovieByID(context.Context, *ID) (*MovieInfo, error)
	CreateMovie(context.Context, *MovieInfo) (*ID, error)
	UpdateMovieByID(context.Context, *MovieInfo) (*Status, error)
	DeleteMovieByID(context.Context, *ID) (*Status, error)
}

// UnimplementedUpvotesServer can be embedded to have forward compatible implementations.
type UnimplementedUpvotesServer struct {
}

func (*UnimplementedUpvotesServer) GetMovies(req *Empty, srv Upvotes_GetMoviesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMovies not implemented")
}
func (*UnimplementedUpvotesServer) GetMovieByID(ctx context.Context, req *ID) (*MovieInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovieByID not implemented")
}
func (*UnimplementedUpvotesServer) CreateMovie(ctx context.Context, req *MovieInfo) (*ID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMovie not implemented")
}
func (*UnimplementedUpvotesServer) UpdateMovieByID(ctx context.Context, req *MovieInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMovieByID not implemented")
}
func (*UnimplementedUpvotesServer) DeleteMovieByID(ctx context.Context, req *ID) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMovieByID not implemented")
}

func RegisterUpvotesServer(s *grpc.Server, srv UpvotesServer) {
	s.RegisterService(&_Upvotes_serviceDesc, srv)
}

func _Upvotes_GetMovies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpvotesServer).GetMovies(m, &upvotesGetMoviesServer{stream})
}

type Upvotes_GetMoviesServer interface {
	Send(*MovieInfo) error
	grpc.ServerStream
}

type upvotesGetMoviesServer struct {
	grpc.ServerStream
}

func (x *upvotesGetMoviesServer) Send(m *MovieInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _Upvotes_GetMovieByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpvotesServer).GetMovieByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviesapp.Upvotes/GetMovieByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpvotesServer).GetMovieByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Upvotes_CreateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpvotesServer).CreateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviesapp.Upvotes/CreateMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpvotesServer).CreateMovie(ctx, req.(*MovieInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Upvotes_UpdateMovieByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpvotesServer).UpdateMovieByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviesapp.Upvotes/UpdateMovieByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpvotesServer).UpdateMovieByID(ctx, req.(*MovieInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Upvotes_DeleteMovieByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpvotesServer).DeleteMovieByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moviesapp.Upvotes/DeleteMovieByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpvotesServer).DeleteMovieByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Upvotes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moviesapp.Upvotes",
	HandlerType: (*UpvotesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovieByID",
			Handler:    _Upvotes_GetMovieByID_Handler,
		},
		{
			MethodName: "CreateMovie",
			Handler:    _Upvotes_CreateMovie_Handler,
		},
		{
			MethodName: "UpdateMovieByID",
			Handler:    _Upvotes_UpdateMovieByID_Handler,
		},
		{
			MethodName: "DeleteMovieByID",
			Handler:    _Upvotes_DeleteMovieByID_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMovies",
			Handler:       _Upvotes_GetMovies_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "moviesapp.proto",
}
